logging:
#  level:
#    org.springframework: INFO
#    com.finartz: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS, Europe/Istanbul}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %yellow(%X{correlationId}){faint} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS, Europe/Istanbul}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%X{correlationId}){faint} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wex"
